#!/bin/bash

# Rate Limiting Test Script
# This script helps verify the rate limiting feature works correctly

echo "🔒 Rate Limiting Feature Test"
echo "=============================="
echo ""
echo "This test will verify:"
echo "  1. Failed login attempts are tracked"
echo "  2. Lockout occurs after 5 failed attempts"
echo "  3. Countdown timer works correctly"
echo "  4. Successful login clears attempts"
echo ""
echo "📱 Steps to test manually:"
echo ""
echo "1. Open the app on iOS Simulator or Android Emulator"
echo "2. Navigate to Login screen"
echo "3. Enter email: test@example.com"
echo "4. Enter password: wrongpassword"
echo "5. Tap 'Sign In'"
echo "6. Repeat steps 4-5 five times"
echo ""
echo "✅ Expected results:"
echo "   - After 3 failed attempts: Yellow warning '2 attempts remaining'"
echo "   - After 5 failed attempts: Red lockout message with countdown"
echo "   - Submit button becomes disabled"
echo "   - Countdown timer counts down from 5:00"
echo ""
echo "7. To test successful login clears attempts:"
echo "   - Wait 5 minutes (or clear app data)"
echo "   - Login with correct credentials"
echo "   - Logout"
echo "   - Try failed login again - should have 5 attempts available"
echo ""
echo "🧪 To run Maestro tests:"
echo "   maestro test .maestro/rate-limit-verify.yaml"
echo ""
echo "📸 Screenshots will be saved to verify UI states"
echo ""
